### ISSUE TITLE
How will SA0102 syntax errors fixed in regular StyleCop be handled?

### ISSUE THREAD

**Issue by mgroetan** [StyleCop/StyleCop.ReSharper#10]
A few false positive SA0102 syntax errors have lately been fixed in the regular StyleCop repo, but no official version has been made yet:

1. https://github.com/StyleCop/StyleCop/pull/194

1. https://github.com/StyleCop/StyleCop/pull/197

Will these fixes be available through the ReSharper extension, or does some code need to be merged?

**Comment by matkoch** [comment]
I just released a new version https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/2018.3.0-beta001 which references StyleCop 6.0.0-beta04.
