### ISSUE TITLE
SA0102 syntax error when nullable value or enum type value inside tuple type

### ISSUE THREAD

**Issue by PlusoneWang** [StyleCop/StyleCop.ReSharper#17]
Please forgive me for being bad in English. It's not my native language.
A Nullable value like ```int?``` inside tuple type will cause syntax error.
```C#
(int? val, string str) DoSomething() // this line cause SA0102 error
{
    // Do something...
    return (null, null);
}
```

**Comment by PlusoneWang** [comment]
Another
```C#
(bool isTrue, MyClass.MyEnum enumValue) DoSomething() // this line cause SA102 error
{
    // Do something...
    return (true, MyClass.MyEnum.AType);
}
```

**Comment by PlusoneWang** [comment]
I use `using static MyClass` to resolve the enum type error.
Something like this:
```C#
// the top of file
using static MyNamespace.MyClass;

// some code...

(bool isTrue, MyEnum enumValue) DoSomething() // this line now NOT cause SA0102 error
{
    // Do something...
    return (true, MyEnum.AType);
}
```

**Comment by Jothay** [comment]
I can confirm this behavior:

`(string typeKey, int? storeID, int? vendorID, int? ilID, int? destID, bool nothingToShip) targetGroupingKey`

throws the SA0102, but when I tried

`(int typeKey, int storeID, int vendorID, int ilID, int destID, bool nothingToShip) targetGroupingKey`

Where nothing is nullablem the error goes away

**Comment by PlusoneWang** [comment]
In fact, for databases that have existed for more than 6 years and have been used in several different technology systems, it is difficult to change the nullable numeric type to not allow null values.

**Comment by PlusoneWang** [comment]
> I can confirm this behavior:
> 
> `(string typeKey, int? storeID, int? vendorID, int? ilID, int? destID, bool nothingToShip) targetGroupingKey`
> 
> throws the SA0102, but when I tried
> 
> `(int typeKey, int storeID, int vendorID, int ilID, int destID, bool nothingToShip) targetGroupingKey`
> 
> Where nothing is nullable the error goes away.

In fact, for databases that have existed for more than 6 years and have been used in several different technology systems, it is difficult to change the nullable numeric type to not allow null values.

**Comment by matkoch** [comment]
I can't transfer the issue, but it belongs to https://github.com/StyleCop/StyleCop most certainly.
