### ISSUE TITLE
Plugin not detected

### ISSUE THREAD

**Issue by fleed** [StyleCop/StyleCop.ReSharper#23]
I have two different VMs with Resharper and the Stylecop extensions, but the plugin is actually working only on one of the two (the older one).

I don't remember if I installed something specific on the first VM, but if I search for `stylecop` in the **options** I see different results.
The most notable difference is that the first VM (the working one) displays a `stylecop` entry under **tools**, with some information like the plugin dll version.

Should I install something else on the second VM to make the plugin work?

**Comment by matkoch** [comment]
Seems that in  one of you're installation the plugin is actually not installed. What does the extension manager show you? And most importantly, what ReSharper/VisualStudio versions do you have?

**Comment by fleed** [comment]
@matkoch I completely uninstalled the extension, restarted visual studio, reinstalled the extension and restarted once more. Now I see the entry in the `tools` section of the settings and it is now working as expected.

Thank for help.
