### ISSUE TITLE
Support for ReSharper 2019.2

### ISSUE THREAD

**Issue by fleed** [StyleCop/StyleCop.ReSharper#25]
After upgrading to ReSharper Ultimate 2019.2, I cannot find the plugin anymore.
Is an update of the extension required? Any timeline available?

**Comment by matkoch** [comment]
It's already  uplodated: https://plugins.jetbrains.com/plugin/11619-stylecop-by-jetbrains/versions

I think it just needs some time to propagate to the plugin feed.
