### ISSUE TITLE
Ability to disable SA0102 in resharper settings

### ISSUE THREAD

**Issue by adelikat** [StyleCop/StyleCop.ReSharper#28]
Often new language features come out and there's a lag time before this extension gets the update, and it has false positives and shows compile errors.

It would be nice to be able to disable this one, since during these times (as of this writing, it is C#8 and inline usings) we can turn off the false positive.  Instead I have to uninstall the extension and just try to remember to check in periodically until those things are addressed.

Since this is a resharper extension inside of visual studio, both of which are more than capable of catching compile errors, this is a rather unnecessary addition anyway, so it makes sense for it to be an option.

**Comment by talhazengin** [comment]
Absolutely we need this kind of solution.

**Comment by matkoch** [comment]
We built against the [latest StyleCop release](https://github.com/StyleCop/StyleCop.ReSharper/blob/master/src/StyleCop.ReSharper/packages.config#L77). You probably meant to create this issue in https://github.com/StyleCop/StyleCop

**Comment by adelikat** [comment]
Are you saying that the options in the Resharper config are controlled by the StyleCop repository?

**Comment by matkoch** [comment]
The ReSharper extension invokes StyleCop in the background, and then forwards the reported code violations. If you want to disable SA0102 then you need to do it in the StyleCop.Settings, which will then also reflect on your CI infrastructure.

**Comment by talhazengin** [comment]
Even if the core StyleCop repo is not maintained by JetBrains. You guys should think about moving the core StyleCop repo under to your development. There is a future in this extension. 
We are locked in C# 7.3 very badly.

**Comment by csdahlberg** [comment]
Personally, I think it'd be more practical to migrate R# to the Roslyn-based StyleCopAnalyzers project than try to continue to update the StyleCop "Classic" parser. That said, I'd still gladly work with JetBrains if they want to take over more of the StyleCop "Classic" development.
