### ISSUE TITLE
switch pattern problem

### ISSUE THREAD

**Issue by NickRimmer** [StyleCop/StyleCop.ReSharper#30]
Is it possible to mute only this errors type somehow? I've tried mute it by "Ignore all such Errors" - but it doesn't help me.

Or will be much better, if I can configure StyleCop rules to work with switch patterns. Cause there is now error, this is correct code.

![image](https://user-images.githubusercontent.com/1754265/67570090-daa13680-f730-11e9-82e6-1dfb5d46a26b.png)

**Comment by NickRimmer** [comment]
Oh, I'm sorry. I found same questions in base project.
https://github.com/StyleCop/StyleCop/issues/154
https://github.com/StyleCop/StyleCop/issues/106

**Comment by matkoch** [comment]
This is an issue on the https://github.com/StyleCop/StyleCop end
