### ISSUE TITLE
Support for Switch Expressions

### ISSUE THREAD

**Issue by Zumpel96** [StyleCop/StyleCop.ReSharper#41]
If I use a switch expression, StyleCop Rule `SA0102` gets triggered.

Example Code:
 ```csharp          
var value = myEnum switch
   {
      customEnum.ValueA => "A",
      customEnum.ValueB => "B",
         _ => "C",
   };
```

Please enable support for switch expressions.

**Comment by matkoch** [comment]
The extension uses the official StyleCop library, which doesn't receive any major development anymore (https://github.com/StyleCop/StyleCop). That also means that new language features aren't supported. I'm suggesting trying the [StyleCop Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers).
