### ISSUE TITLE
Support for C# 8

### ISSUE THREAD

**Issue by IvanLieckens** [StyleCop/StyleCop.ReSharper#44]
I've started encountering many instances of SA0102 after applying ReSharper recommendations to optimize my syntax due to C# 8 features not being supported by StyleCop causing those lines to be marked as red line.

**Comment by matkoch** [comment]
Please see the statement on the official repository: https://github.com/StyleCop/StyleCop

**Comment by IvanLieckens** [comment]
So to ensure that ReSharper uses the right formatting I should install this extension, then disable the analysis by it, install the new Analyzers and get the feedback from there?

**Comment by matkoch** [comment]
you don't need this extension fir the analyzers

**Comment by powerdude** [comment]
What about code cleanup?  Does Resharper do the same amount of cleanup with the suggested analyzer without the extension that it does with the extension?  I don't seem to get the same results with just the analyzer and Resharper.

**Comment by matkoch** [comment]
I don’t know off-hand, but ReSharper should be able to react to stylecop
analyzer settings.

**Comment by IvanLieckens** [comment]
Well for now I have installed the Analyzers and disabled the "analyse as you type" in the settings of the extension and things are looking good, did have to create supression files per project for the analyzers now instead of having ReSharper Options handling computer/solution/shared settings but things work like this :)

**Comment by matkoch** [comment]
Great to hear. Like you said you may uninstall the extension if you’re only
using the analyzers.
