### ISSUE TITLE
C# version supported

### ISSUE THREAD

**Issue by Fabman08** [StyleCop/StyleCop.ReSharper#46]
Hi guys!
I'm sorry but I can't find wich C# versions are supported in the current release.
I've encoutered problems with C# 8.0 and C# 9.0.

Anyone can point out thw supported versions or how configure c# versions on the extension?

Thank you

**Comment by matkoch** [comment]
The plugin uses the original https://github.com/StyleCop/StyleCop repository, which is not under our control and which itself gives the recommendation to consider moving to https://github.com/DotNetAnalyzers/StyleCopAnalyzers. There's not much we can do here.
