### ISSUE TITLE
StyleCop has error Rule: SA0102 when use file scoped namespace New Language Features of C# 10

### ISSUE THREAD

**Issue by mohrmz** [StyleCop/StyleCop.ReSharper#53]
StyleCop has error Rule: SA0102 when use file scoped namespace New Language Features of C# 10 

> `namespace WorkShop1;`
> `public class Class1`
> `{`
> 
> `}`
> 

![Screenshot 2022-06-05 154723](https://user-images.githubusercontent.com/34716164/172048096-e93caa72-f3e4-4a3d-992d-2b80639e0aea.png)

**Comment by matkoch** [comment]
Please see the notice from StyleCop:

https://github.com/StyleCop/StyleCop
