### ISSUE TITLE
StyleCop extension listed as “incompatible” and not working with latest version of ReSharper

### ISSUE THREAD

**Issue by Infarinato** [StyleCop/StyleCop.ReSharper#55]
In both Visual Studio 2019 (Version 16.11.18) and 2022 (Version 17.3.1) the StyleCop extension is now listed as “incompatible” and doesn’t seem to be working with the latest version of ReSharper (2022.2.1): StyleCop rules no longer appear in the ReSharper options and are ignored by ReSharper upon refactoring.&nbsp;☹

![image](https://user-images.githubusercontent.com/365768/185879490-686c2d4c-60de-4181-8bac-28c1b70f7378.png)

**Comment by matkoch** [comment]
Could you try disabling the plugin verifier under options?

Question beside, have you ever considered moving to the StyleCop Analyzers NuGet package? StyleCop (the main project) is no longer maintained, so there's no support for new language features.

**Comment by Infarinato** [comment]
That was it, Matthias, thanks!&nbsp;👍 Uninstalling the StyleCop extension, disabling the extension verifier under Options > Environment > Extension Manager and then reinstalling the extension did the trick.&nbsp;😅

I wasn’t aware of StyleCop Analyzers NuGet package&nbsp;😮: that looks more flexible (though quite a bit more work to set up at the start). But more importantly, I wasn’t aware of the fact that it was the recommended approach now, and that the extension itself was being deprecated…&nbsp;😐

**Comment by matkoch** [comment]
@powerdude not really. Since the original project is no longer continued, the ReSharper plugin is also in a kind of "low-maintenance mode", where we only update for newer ReSharper versions. If it works, great; but if not, I really recommend looking for alternatives.

**Comment by powerdude** [comment]
ok, thanks.

**Comment by ulex** [comment]
This issue should be fixed in ReSharper 2022.2.**2**. Disabling extension verifier is only temporary workaround to this problem.
