### ISSUE TITLE
please update to 2024.1

### ISSUE THREAD

**Issue by lgitt** [StyleCop/StyleCop.ReSharper#61]
please update to 2024.1

**Comment by jalbertSyncroTech** [comment]
Seconded.

I was able to make a patch, and then run `.\buildPlugin.ps1 "2024.1.1"`.
[StyleCopResharper202411.patch](https://github.com/StyleCop/StyleCop.ReSharper/files/15079391/StyleCopResharper202411.patch)

**Comment by matkoch** [comment]
sorry for the late response, the plugin has been published now
