### ISSUE TITLE
SA1009 False positive for ValueTuple

### ISSUE THREAD

**Issue by Agoebel195** [StyleCop/StyleCop.ReSharper#9]
The following code causes 2 false positives for SA1009:
        public static List<(string, string)> GetValueTuple()
        {
            return new List<(string, string)>();
        }

**Comment by matkoch** [comment]
Could you recreate this issue in the `StyleCop/StyleCop` repository? This here is for the ReSharper extension.

**Comment by matkoch** [comment]
I guess you should follow this: https://github.com/StyleCop/StyleCop/issues/141
